// ... existing code ...
const teamRoutes = require('./routes/teamRoutes');
const teamWarRoutes = require('./routes/teamWarRoutes');

// ... existing code ...
app.use('/api', teamRoutes);
app.use('/api', teamWarRoutes);
// ... existing code ...